//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NyayaDesk.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advocate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Advocate()
        {
            this.AdvocateDocuments = new HashSet<AdvocateDocument>();
            this.AdvocateExperiences = new HashSet<AdvocateExperience>();
            this.AdvocatePracticeAreas = new HashSet<AdvocatePracticeArea>();
            this.AdvocateQualifications = new HashSet<AdvocateQualification>();
        }
    
        public int AdvocateId { get; set; }
        public int UserId { get; set; }
        public string EnrollmentNumber { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public string EnrollmentState { get; set; }
        public string EnrollmentCertificatePath { get; set; }
        public string BarCouncilName { get; set; }
        public string BarCouncilRegistrationNo { get; set; }
        public string AdvocateType { get; set; }
        public string OfficeName { get; set; }
        public string OfficeAddress { get; set; }
        public string OfficePhone { get; set; }
        public string OfficeMobile { get; set; }
        public string OfficeEmail { get; set; }
        public string WebsiteUrl { get; set; }
        public string ProfessionalSummary { get; set; }
        public decimal YearsOfExperience { get; set; }
        public decimal ConsultationFee { get; set; }
        public Nullable<int> CourtTypeId { get; set; }
        public Nullable<int> CourtId { get; set; }
        public string LanguagesKnown { get; set; }
        public bool IsAvailableForOnlineConsultation { get; set; }
        public int TotalCases { get; set; }
        public int WonCases { get; set; }
        public int LostCases { get; set; }
        public int PendingCases { get; set; }
        public decimal Rating { get; set; }
        public bool IsVerified { get; set; }
        public Nullable<System.DateTime> VerificationDate { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public string Remarks { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual Court Court { get; set; }
        public virtual CourtType CourtType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvocateDocument> AdvocateDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvocateExperience> AdvocateExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvocatePracticeArea> AdvocatePracticeAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvocateQualification> AdvocateQualifications { get; set; }
    }
}
