//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NyayaDesk.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvocateDocument
    {
        public int AdvocateDocumentId { get; set; }
        public int AdvocateId { get; set; }
        public int DocumentTypeId { get; set; }
        public string DocumentTitle { get; set; }
        public string DocumentNumber { get; set; }
        public string IssuingAuthority { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string FileName { get; set; }
        public string OriginalFileName { get; set; }
        public string FileExtension { get; set; }
        public Nullable<long> FileSizeKB { get; set; }
        public string MimeType { get; set; }
        public string FilePath { get; set; }
        public bool IsVerified { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public string Remarks { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual Advocate Advocate { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual User User { get; set; }
    }
}
