//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NyayaDesk.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvocateQualification
    {
        public int AdvocateQualificationId { get; set; }
        public int AdvocateId { get; set; }
        public string DegreeName { get; set; }
        public string Specialization { get; set; }
        public string UniversityName { get; set; }
        public string CollegeName { get; set; }
        public int PassingYear { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string Grade { get; set; }
        public string CertificateNumber { get; set; }
        public string CertificatePath { get; set; }
        public string Remarks { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsHighestQualification { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual Advocate Advocate { get; set; }
    }
}
