//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NyayaDesk.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvocateExperience
    {
        public int AdvocateExperienceId { get; set; }
        public int AdvocateId { get; set; }
        public string OrganizationName { get; set; }
        public string PositionHeld { get; set; }
        public string ExperienceType { get; set; }
        public string PracticeArea { get; set; }
        public System.DateTime FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public bool IsCurrent { get; set; }
        public Nullable<int> TotalExperienceMonths { get; set; }
        public string Responsibilities { get; set; }
        public string Achievements { get; set; }
        public string CertificatePath { get; set; }
        public string ReferenceName { get; set; }
        public string ReferenceMobile { get; set; }
        public string ReferenceEmail { get; set; }
        public string Remarks { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual Advocate Advocate { get; set; }
    }
}
