//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NyayaDesk.Web.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Court
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Court()
        {
            this.Advocates = new HashSet<Advocate>();
        }
    
        public int CourtId { get; set; }
        public int CourtTypeId { get; set; }
        public int DistrictId { get; set; }
        public string CourtName { get; set; }
        public string CourtCode { get; set; }
        public string Address { get; set; }
        public string PinCode { get; set; }
        public string ContactNumber { get; set; }
        public string EmailAddress { get; set; }
        public string WebsiteUrl { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Advocate> Advocates { get; set; }
        public virtual CourtType CourtType { get; set; }
        public virtual District District { get; set; }
    }
}
